<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $hospitalName }}</title>


    <style>
        table,
        td,
        th {
            border: 1px solid black;
        }

        table.head_info td {
            border: 0px !important;
            margin: 0px;
        }

        table.head_info {
            border: 0px !important;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        table tr,
        td {
            padding: 5px
        }

        h2 {
            text-align: center
        }

        .address p,
        h2 {
            text-align: center;
            margin: 0 auto;
        }

        table.comt_sign td {
            border: 0px !important;
            margin: 0px;
        }

        table.comt_sign {
            border: 0px !important;
        }
    </style>



</head>

<body>
    <div class="address">
        <h2>{{ $hospitalName }}</h2>
        <p>{{ $hospitalAddress }} | Mobile: {{ $hospitalPhone }}</p>
        <br>
        <br>
        <br>
    </div>
    <span style="border:1px solid #bbbbbb;padding:5px">Accounts</span>
    <br><br>
    <table id="printable" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th scope="col" class="notForPrint">No.</th>
                <th scope="col">Detials</th>
                <th scope="col">Amount(TK)</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <th scope="row">1</th>
                <td>Indoor</td>
                <td>{{ $indoors }}</td>
            </tr>

            <tr>
                <th scope="row">2</th>
                <td>Outdoor</td>
                <td>{{ $outdoor }}</td>
            </tr>

            <tr>
                <th scope="row">3</th>
                <td>Others</td>
                <td> {{ $income }} </td>
            </tr>
            <tr class="marking">
                <th scope="row">4</th>
                <td>Total</td>
                <td>{{ $total_income }}</td>
            </tr>
            <tr class="marking">
                <th scope="row">5</th>
                <td>Expenditure</td>
                <td>{{ $expenditure }}</td>
            </tr>

            <tr class="income_amount">
                <th scope="row">6</th>

                <td><b>Cash:</b></td>
                <td><b>{{ number_format($total_income - $expenditure) }}</b></td>
            </tr>


            <tr class="due">
                <th scope="row">7</th>
                <td><b>Due Amount:</b></td>
                <td><b> {{ $due }} (All Patient)</b></td>
            </tr>
            <tr class="due">
                <th scope="row">8</th>
                <td><b>Due Collected:</b></td>
                <td><b> {{ $dueCollection }}</b></td>
            </tr>
        </tbody>
        <tfoot>
            <th>##</th>
            <th colspan="1"><span class="title_bar">Result Between:
                    {{ $startDate->toFormattedDateString() }} -
                    {{ $endDate->toFormattedDateString() }}&nbsp;&nbsp;!</span>
            </th>
            <th>
                {{-- <span class="bf">BF: {{ $previousDayIncome }}</span> --}}
            </th>
        </tfoot>
    </table>
    <br>
    <br>
    <br>
    <table class="comt_sign">
        <tr>
            <td>&nbsp;&nbsp;Comments <br> -----------------</td>
            <td style="text-align: right">Signature &nbsp;&nbsp; <br>---------------</td>
        </tr>
    </table>

    <br>
    <br>
    <br>
    <br>
    <br>

    <table class="head_info">
        <tr>
            <td style="font-size: 12px">Generated By __ {{ Auth::user()->name }}</td>
        </tr>
    </table>
</body>

</html>
