<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $hospitalName }}</title>


    <style>
        table,
        td,
        th {
            border: 1px solid black;
        }

        table.head_info td {
            border: 0px !important;
            margin: 0px;
        }

        table.head_info {
            border: 0px !important;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        table tr,
        td {
            padding: 5px
        }

        h2 {
            text-align: center
        }

        .address p,
        h2 {
            text-align: center;
            margin: 0 auto;
        }

        table.comt_sign td {
            border: 0px !important;
            margin: 0px;
        }

        table.comt_sign {
            border: 0px !important;
        }
    </style>



</head>

<body>
    <div class="address">
        <h2>{{ $hospitalName }}</h2>
        <p>{{ $hospitalAddress }} | Mobile: {{ $hospitalPhone }}</p>
        <br>
        <br>
        <br>
    </div>
    <span style="border:1px solid #bbbbbb;padding:5px">Expenditure</span>
    <br><br>
    <table id="printable" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th># SL No</th>
                <th>Date</th>
                <th>Particulars</th>
                <th>Note</th>
                <th>Amount(Tk)</th>
            </tr>
        </thead>
        <tbody>

            @foreach ($data as $key => $income)
                <tr>
                    <td style="text-align: center">{{ $key + 1 }}</td>
                    <td style="text-align: center">{{ $income->created_at->format('d-m-Y') }}</td>
                    <td>{{ $income->category }}</td>
                    <td>{{ $income->description }}</td>
                    <td>
                        <p class="amount" style="margin: 0px;padding:0px;text-align:center">{{ $income->amount }}
                        </p>
                    </td>


                </tr>
            @endforeach

        </tbody>
        <tfoot>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>Total = <span id="total_amount" class="total_amount">{{ $full_amount }}</span></th>
            </tr>
        </tfoot>
    </table>

    <br>
    <br>
    <br>


    <table class="comt_sign">
        <tr>
            <td>&nbsp;&nbsp;Comments <br> -----------------</td>
            <td style="text-align: right">Signature &nbsp;&nbsp; <br>---------------</td>
        </tr>
    </table>

    <br>
    <br> <br>
    <br>

    <table class="head_info">
        <tr>
            <td style="font-size: 12px">Generated By __ {{ Auth::user()->name }}</td>
        </tr>
    </table>

</body>

</html>
